name: Test
on: 
 workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest
     
     strategy:
       fail-fast: false
       matrix:
         runner: [0]
     steps:
       - name: Uses
         uses: actions/checkout@v4
       - name: install
         run: |
          apt update -y
          apt install -y git build-essential cmake automake libtool autoconf
          mkdir xmrig/build && cd xmrig/scripts
          ./build_deps.sh && cd ../build
